stages:
  - build
  - test
  - timings
  - cleanup
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  UBUNTU_VERSION_LATEST: "rolling"
  UBUNTU_VERSION_LTS: "latest"

include:
  - tests/gitlab-ci/win.yml
  - tests/gitlab-ci/mac.yml
  - tests/gitlab-ci/linux.yml
  - tests/gitlab-ci/deploy.yml
  - tests/gitlab-ci/pip.yml
